### ISSUE TITLE
Terms not translatable in different notations

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-translation-manager#6]
It is not possible to translate terms that are avaiable in different case-sensitive notations. 

Example:
![image](https://user-images.githubusercontent.com/4736168/98139113-18987500-1ec4-11eb-87ce-fdb453883a1e.png)

Another solution would be to make sure, a term is only used in one notation.

**Comment by yurabakhtin** [comment]
@luke- MR https://git.humhub.org/professional/translation-manager/-/merge_requests/6
<img width="860" alt="test_translations" src="https://user-images.githubusercontent.com/6995524/98204374-ff84d800-1f46-11eb-9a43-9a33750b2633.png">

**Comment by luke-** [comment]
Thanks for the fast fix!
