### ISSUE TITLE
Improve Table

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-translation-manager#7]
![image](https://user-images.githubusercontent.com/4736168/107069303-10611600-67e2-11eb-9e88-5f66b1653667.png)

**Comment by buddh4** [comment]
Probably related to https://github.com/humhub/wording/issues/26

**Comment by yurabakhtin** [comment]
@luke- MR https://git.humhub.org/professional/translation-manager/-/merge_requests/8

@buddh4 I see `body {... word-break: break-word; ...}` in the `theme.css` and I found `.table-responsive {... word-wrap: normal; ...}` and applied this class to the tables in this module.
